//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_location_upd
    {
        public int id { get; set; }
        public string old_street_address { get; set; }
        public string new_street_address { get; set; }
        public string old_postal_code { get; set; }
        public string new_postal_code { get; set; }
        public string old_city { get; set; }
        public string new_city { get; set; }
        public string old_state_province { get; set; }
        public string new_state_province { get; set; }
        public string old_country_id { get; set; }
        public string new_country_id { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
    }
}
