//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_employee_upd
    {
        public int id { get; set; }
        public string old_first_name { get; set; }
        public string new_first_name { get; set; }
        public string old_last_name { get; set; }
        public string new_last_name { get; set; }
        public string old_email { get; set; }
        public string new_email { get; set; }
        public string old_phone_number { get; set; }
        public string new_phone_number { get; set; }
        public Nullable<System.DateTime> old_hire_date { get; set; }
        public Nullable<System.DateTime> new_hire_date { get; set; }
        public Nullable<int> old_job_id { get; set; }
        public Nullable<int> new_job_id { get; set; }
        public Nullable<decimal> old_salary { get; set; }
        public Nullable<decimal> new_salary { get; set; }
        public Nullable<int> old_manager_id { get; set; }
        public Nullable<int> new_manager_id { get; set; }
        public Nullable<int> old_department_id { get; set; }
        public Nullable<int> new_department_id { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
    }
}
