//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_region_ins_del
    {
        public int region_id { get; set; }
        public string region_name { get; set; }
        public string process_type { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
    }
}
