//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_job_upd
    {
        public int id { get; set; }
        public string old_job_title { get; set; }
        public string new_job_title { get; set; }
        public Nullable<decimal> old_min_salary { get; set; }
        public Nullable<decimal> new_min_salary { get; set; }
        public Nullable<decimal> old_max_salary { get; set; }
        public Nullable<decimal> new_max_salary { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
    }
}
