//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHomeWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log_country_upd
    {
        public string country_id { get; set; }
        public string old_country_name { get; set; }
        public string new_country_name { get; set; }
        public Nullable<int> old_region_id { get; set; }
        public Nullable<int> new_region_id { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
    }
}
